Array Iterating

In [9]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr.shape)
for i in arr:
    print(i)

(2, 2, 3)
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [6]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in arr:
    for j in i:
        for k in j:
            print(k)


1
2
3
4
5
6
7
8
9
10
11
12


Iterate Arrays with nditer()

In [18]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
