Array Reshaping

In [24]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,1,3))
print(arr.ndim)

[[[1 2 3]]

 [[4 5 6]]]
1


Flattenig an Array 

In [27]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.reshape(-1))

[1 2 3 4 5 6 7 8]


Array Iterating