Accessing 1D array


In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[3])
print(arr[3] + arr[4])

4
9


Accessing 2D Array

In [6]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,3])
print(arr[1,3])



4
8


Accessing 3D Array

In [5]:
import numpy as np 
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15], [16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35]]])
print(arr)
# print(arr[0,0,:])
print(arr.flatten())

# for row in arr[0]:  # Looping through rows
#     print(row)
print(arr.ndim)


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35]
3
