Random Array

In [19]:
from numpy import random
random_array = random.randint(20, size=(5, 5))
print(random_array)

random_array_float = round(random.rand() * 5, 2)
print(random_array_float)

[[ 5 19  3  4 10]
 [15  6  0  2 10]
 [ 7 19  1  1 11]
 [18 14  3  3 13]
 [14  5  6  1  1]]
2.24


Random Numbers from an Array

In [35]:
from numpy import random
random_element = random.choice([0,1,4,5,7,10,11,13,15])

print(random_element)

11
