0D and 1D array

In [9]:
import numpy as np
n = np.array([1,2,3,4,5])
print(n.ndim)

arr_0D = np.array(123)
print(arr_0D.ndim)
print(type(arr_0D))

1
0
<class 'numpy.ndarray'>


2D Array

In [1]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


3D Array

In [3]:
import numpy as np 
arr = np.array([[[1,2,3], [4,5,6]]])
print(arr)
print(arr.shape)
print(arr.ndim)


[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)
3


In [2]:
import numpy as np
arr = np.array([[1,2,3],[3,4,5]], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3]
    [3 4 5]]]]]
5
