Array Indexing

In [17]:
import numpy as np 

# arr = np.array([1,2,3, "Talib"], ndmin=10)
# print(arr)

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2[0,0])
print(arr2[0,2])
print(arr2[1,0])
print(arr2[1,1])
print(arr2[2,0])
print(arr2[2,2])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

1
3
4
5
7
9
6


In [32]:
arr = np.array([[10, 20, 30, 40, 50, 60], [6, 5, 4, 3, 2, 1]])
newShape = arr.reshape(4, 3)
print(newShape)

[[10 20 30 40]
 [50 60  6  5]
 [ 4  3  2  1]]
