Sorting Array

In [3]:
import numpy as np
arr = np.array([2,5,8,4,3,1])
print(np.sort(arr))

arr2 = np.array([True, False, False, True])
print(np.sort(arr2))

[1 2 3 4 5 8]
[False False  True  True]


Sorting an 2D array

In [7]:
import numpy as np
arr = np.array([[1,3,2,4,5], [8,7,6,9,10]])
print(np.sort(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
